import { filledInReportData } from "./filled-in-report";
import { createReport } from "./create-report";

export const reports = [
  {
    name: "Bila team platform",
    data: createReport,
    status: "draft",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "fVjjVCLscZ",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "submitted",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "v4s6gZJeoQ",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "approved",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "BsmCMrQzq6",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "rejected",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "uc7DLfHEyo",
  },
  {
    name: "Bila team platform",
    data: createReport,
    status: "draft",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "5t2Xo49d7T",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "submitted",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "npRD28B7pw",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "approved",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "xlgi6Bpi3e",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "rejected",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "ZMfsOGIo5X",
  },
  {
    name: "Bila team platform",
    data: createReport,
    status: "draft",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "HZGGSXZ0RT",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "submitted",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "LiIvLYaq54",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "approved",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "79w37ClSpC",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "rejected",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "R15m3iMDAQ",
  },
  {
    name: "Bila team platform",
    data: createReport,
    status: "draft",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "JlxDCFEnAx",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "submitted",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "zZtrUY2NTx",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "approved",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "lGeS58v6zf",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "rejected",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "FKfEs6YdOO",
  },
  {
    name: "Bila team platform",
    data: createReport,
    status: "draft",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "OwVjWjh5CF",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "submitted",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "XvJ6d5ZUgf",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "approved",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "hcWVRzj9sQ",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "rejected",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "ytDZynllRm",
  },
  {
    name: "Bila team platform",
    data: createReport,
    status: "draft",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "PK4Mi5RgbA",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "submitted",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "Bfl1PepSRQ",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "approved",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "we293qLCkA",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "rejected",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "jnakjfPs8m",
  },
  {
    name: "Bila team platform",
    data: createReport,
    status: "draft",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "m6KgXZgjDr",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "submitted",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "cFo3TxjjqU",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "approved",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "0kQBo3Fzie",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "rejected",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "7ADDRntajW",
  },
  {
    name: "Bila team platform",
    data: createReport,
    status: "draft",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "RDfEjdXX1G",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "submitted",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "nLfKYfBmua",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "approved",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "Bch3ddCpMb",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "rejected",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "13qlnCagrs",
  },
  {
    name: "Bila team platform",
    data: createReport,
    status: "draft",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "fsWY4j1OT5",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "submitted",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "b5zJrAwsVg",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "approved",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "8yoMvv576i",
  },
  {
    name: "Bila team platform",
    data: filledInReportData,
    status: "rejected",
    manager: "John Doe",
    author: "Jill Doe",
    created_at: "2024-01-01T00:00:00Z",
    id: "8LCiOVSgRw",
  },
];
